// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: click_logs.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getByDateRange = `-- name: GetByDateRange :many
SELECT 
    DATE_TRUNC('day', cl.clicked_at)::timestamp AS date,
    COUNT(*) AS total_click
FROM click_logs cl
LEFT JOIN links l ON l.short_code = cl.code OR l.custom_short_code = cl.code
WHERE cl.clicked_at BETWEEN $2::timestamp AND $3::timestamp AND l.user_id = $1
GROUP BY DATE_TRUNC('day', cl.clicked_at)
ORDER BY date ASC
`

type GetByDateRangeParams struct {
	UserID   uuid.UUID
	FromDate time.Time
	ToDate   time.Time
}

type GetByDateRangeRow struct {
	Date       time.Time
	TotalClick int64
}

func (q *Queries) GetByDateRange(ctx context.Context, arg GetByDateRangeParams) ([]GetByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getByDateRange, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetByDateRangeRow
	for rows.Next() {
		var i GetByDateRangeRow
		if err := rows.Scan(&i.Date, &i.TotalClick); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertClickLog = `-- name: InsertClickLog :one
INSERT INTO click_logs (
    code,
    ip_address,
    user_agent,
    referrer,
    country,
    traffic,
    device_type,
    browser
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, ip_address, user_agent, referrer, clicked_at, code, country, device_type, traffic, browser
`

type InsertClickLogParams struct {
	Code       string
	IpAddress  sql.NullString
	UserAgent  sql.NullString
	Referrer   sql.NullString
	Country    sql.NullString
	Traffic    sql.NullString
	DeviceType sql.NullString
	Browser    sql.NullString
}

func (q *Queries) InsertClickLog(ctx context.Context, arg InsertClickLogParams) (ClickLog, error) {
	row := q.db.QueryRowContext(ctx, insertClickLog,
		arg.Code,
		arg.IpAddress,
		arg.UserAgent,
		arg.Referrer,
		arg.Country,
		arg.Traffic,
		arg.DeviceType,
		arg.Browser,
	)
	var i ClickLog
	err := row.Scan(
		&i.ID,
		&i.IpAddress,
		&i.UserAgent,
		&i.Referrer,
		&i.ClickedAt,
		&i.Code,
		&i.Country,
		&i.DeviceType,
		&i.Traffic,
		&i.Browser,
	)
	return i, err
}
