// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package database

import (
	"context"
)

const getGlobalTotalClicks = `-- name: GetGlobalTotalClicks :one
SELECT COUNT(*) FROM click_logs
`

func (q *Queries) GetGlobalTotalClicks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getGlobalTotalClicks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalActiveUsers = `-- name: GetTotalActiveUsers :one
SELECT COUNT(*) FROM users 
WHERE is_active = TRUE AND deleted_at IS NULL
`

func (q *Queries) GetTotalActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalLinksCreated = `-- name: GetTotalLinksCreated :one
SELECT COUNT(*) FROM links 
WHERE deleted_at IS NULL
`

func (q *Queries) GetTotalLinksCreated(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalLinksCreated)
	var count int64
	err := row.Scan(&count)
	return count, err
}
