// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ClickLog struct {
	ID         uuid.UUID
	IpAddress  sql.NullString
	UserAgent  sql.NullString
	Referrer   sql.NullString
	ClickedAt  time.Time
	Code       string
	Country    sql.NullString
	DeviceType sql.NullString
	Traffic    sql.NullString
	Browser    sql.NullString
}

type Link struct {
	ID              uuid.UUID
	OriginalUrl     string
	ShortCode       string
	CustomShortCode sql.NullString
	UserID          uuid.UUID
	ExpiredAt       sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}

type RefreshToken struct {
	ID        uuid.UUID
	Token     string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt time.Time
}

type User struct {
	ID              uuid.UUID
	Name            string
	Email           string
	PasswordHash    sql.NullString
	IsActive        bool
	IsVerified      bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
	GoogleID        sql.NullString
	ProfileImageUrl sql.NullString
}
