// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url
FROM users 
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url
FROM users
WHERE google_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users(
    name,
    email,
    password_hash
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url
`

type InsertUserParams struct {
	Name         string
	Email        string
	PasswordHash sql.NullString
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUser, arg.Name, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
	)
	return i, err
}

const insertUserWithGoogle = `-- name: InsertUserWithGoogle :one
INSERT INTO users(
    name,
    email,
    google_id,
    is_verified,
    profile_image_url
) VALUES (
    $1,
    $2,
    $3,
    TRUE,
    $4
)
RETURNING id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url
`

type InsertUserWithGoogleParams struct {
	Name            string
	Email           string
	GoogleID        sql.NullString
	ProfileImageUrl sql.NullString
}

func (q *Queries) InsertUserWithGoogle(ctx context.Context, arg InsertUserWithGoogleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUserWithGoogle,
		arg.Name,
		arg.Email,
		arg.GoogleID,
		arg.ProfileImageUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
name = $1, email = $2, password_hash = $3, is_verified = $4, profile_image_url = $5
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url
`

type UpdateUserParams struct {
	Name            string
	Email           string
	PasswordHash    sql.NullString
	IsVerified      bool
	ProfileImageUrl sql.NullString
	ID              uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.IsVerified,
		arg.ProfileImageUrl,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
	)
	return i, err
}
